name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [$default-branch]
  pull_request:
  workflow_dispatch:

# Only one ci action should run per branch at any one time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # uses .minimum_zig_version from build.zig.zon
      - uses: mlugg/setup-zig@v2

      - name: Compile
        run: zig build -Dbackend=testing

      - name: Run tests
        run: zig build test -Dbackend=testing

  compile:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        backend: [sdl2, sdl3, sdl3gpu, raylib, raylib_zig, glfw, wio, pugl]
        include:
          - # Add one extra job on windows for dx11
            os: windows-latest
            backend: dx11
          - # Add extra args to raylib
            backend: raylib
            args: "-Duse-lld=false"
          - # Add wio with Vulkan renderer
            backend: wio
            args: "-Drenderer=vulkan"
          - # Only compile the web backend on Ubuntu
            os: ubuntu-latest
            backend: web

    runs-on: ${{ matrix.os }}
    name: Compile ${{ matrix.backend }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2

      - name: Install libraries
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mesa-common-dev libgl-dev libglx-dev libegl-dev libgl1-mesa-dev libglu1-mesa-dev \
            libpulse-dev libasound2-dev \
            libxext-dev libxfixes-dev libxrender-dev libx11-dev libxrandr-dev libxi-dev libxcursor-dev libxinerama-dev \
            libwayland-dev libxkbcommon-dev

      - name: Compile
        run: zig build -Dbackend=${{ matrix.backend }} ${{ matrix.args }}
